name: analyze
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: domain to analyze for compatibility levels (empty for example.org)
        required: false
        default: 'example.org'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
    - name: Install
      run: |
        python -m pip install six
    - name: Analyze
      run: |
        ./analyze.py -t ${{ github.event.inputs.hostname || 'example.org' }}
