name: analyze
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        python -m pip install six
    - name: Analyze
      run: |
        ./analyze.py -t example.org
