name: cipherscan

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      hostname:
        description: hostname to cscan (empty for example.org)
        required: false
        default: 'example.org'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Test Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install six
    - name: Scan ${{ github.event.inputs.hostname }}
      run: |
        ./cipherscan ${{ github.event.inputs.hostname || 'example.org' }}
